export const SET_PROFILE = 'SET_PROFILE';
export const SET_USER = 'SET_USER';
// export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_CHANNELS= 'SET_CHANNELS'; 
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL'

