// Định nghĩa các type action

//MESSAGE ACTIONS
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const REVOKE_MESSAGE = 'REVOKE_MESSAGE';
export const GET_MESSAGE = 'GET_MESSAGE';
export const GET_MESSAGES = 'GET_MESSAGE';
export const GET_HISTORY_MESSAGE = 'GET_HISTORY_MESSAGE';


//CHANNEL ACTIONS
export const CREATE_SINGLE_CHAT = 'CREATE_SINGLE_CHAT';
export const CREATE_GROUP_CHAT = 'CREATE_GROUP_CHAT';
export const ADD_SINGLE_CHAT = 'ADD_SINGLE_CHAT';
export const ADD_GROUP_CHAT = 'ADD_GROUP_CHAT';
export const DELETE_SINGLE_CHAT = 'DELETE_SINGLE_CHAT';
export const DELETE_GROUP_CHAT = 'DELETE_GROUP_CHAT';

